### ISSUE TITLE
Unable to run examples: 403 on dataset generation

### ISSUE THREAD

**Issue by ale0xb** [jdfekete/progressivis#5] opened 2018-07-03 15:54 UTC
Hello,

When running `examples/create_nyc_dataset.sh` I'm getting a 403 error for all resources.
If I enter one of the urls (for example [this one](https://storage.googleapis.com/tlc-trip-data/2015/green_tripdata_2015-01.csv)) I can see more details on the error.

**Comment by xtianpoli** [comment] 2018-07-03 19:52
Hi Alex,
Thanks for your feedback, the issue is fixed now. Please consider pulling the repository and running the script again.
Best,
Christian

**Closed** 2018-07-03 19:53 UTC

**Comment by ale0xb** [comment] 2018-07-03 21:39
I can confirm the issue is fixed now. Thanks!
